---
- name: playbook to create users
  hosts: dev
  become: true
  tasks:
   - name: create a user
     user:
      name: "{{ item }}"
      password: "{{ password }}"
      shell: "{{ shelltype }}"
      comment: "{{ comment1 }}"
     with_items:
      - "{{ user1 }}"
      - "{{ user2 }}"
   - name: create a user
     user:
      name: "{{ item }}"
      password: "{{ password }}"
      shell: "{{ shelltype }}"
      comment: "{{ comment2 }}"
     with_items:
      - "{{ user3 }}"
      - "{{ user4 }}"
