---
- name: create a user
  hosts: all
  vars_prompt:
   - name: user
     prompt: "Enter the user name: " 
     private: false
  become: true
  tasks:
   - name: create a user
     user:
      name: "{{ user }}"
     register: output
   - name: print the logs
     debug:
      var: output
   - name: update the password if the user is newly created
     user:
      name: "{{ user }}"
      password: 123456
     when:
      output.changed==true
...
