---
- name: playbook to install elinks, git , maven, tree, apache2, figlet, tomcat10
  hosts: all
  become: true
  tasks:
    - name: uninstall packages
      apt:
       name: ["git", "maven", "tree", "elinks", "apache2", "figlet", "tomcat10"]
       state: absent
       update_cache: yes
...
