---
- name: playbook to install elinks
  hosts: all
  become: true
  tasks:
    - name: install elinks
      apt:
       name: elinks
       state: present
       update_cache: yes
...

#ansible all -m apt -a 'name=elinks state=present update_cache=yes'
