---
- name: playbook to install elinks, git , maven, and uninstall tree, apache2, figlet, tomcat10
  hosts: all
  become: true
  tasks:
   - name: install and uninstall  packages
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: yes
     with_items:
       - {a: elinks, b: present}
       - {a: git, b: present}
       - {a: maven, b: present}
       - {a: tree, b: absent}
       - {a: apache2, b: absent}
       - {a: figlet, b: absent}
       - {a: tomcat10, b: absent}
